export const TOOGLE_APP_LOADING = "TOOGLE_APP_LOADING";
export const SET_SESSION = "SET_SESSION";
export const LOAD_CONTACT_LIST = "LOAD_CONTACT_LIST";
export const FIND_SELECTED_USER = "FIND_SELECTED_USER";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const SEND_MESSAGE = "SEND_MESSAGE";
