export const TOOGLE_APP_LOADING = "TOOGLE_APP_LOADING";
export const LOAD_CONTACT_LIST = "LOAD_CONTACT_LIST";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const SEND_MESSAGE = "SEND_MESSAGE";
